### ISSUE TITLE
Create a table / database for storing model meta data & metrics

### ISSUE THREAD

**Issue by ybressler** [checkifcovid/data-science-experiments#8]
It's important to track how our models progress over time. Assume the application will run once per day. On run, the app might generate anywhere from 10 to 1,000 models – generating valuable metrics on each one. Further, the best performing model will be isolated and saved to the application interface. That model's data can be stored in the same database (new column for "best model") or can be stored in a new table, for memory optimization sake.

Do we want to store all model performance? Or just best model?
- [ ] Just best model
- [ ] All model performance
- [x] Best model per model type (random forests, linear regression, neural network)

**Comment by rashnil-git** [comment]
good to have best model per model type so that they can also be used as ensemble, if needed

**Comment by ybressler** [comment]
Good point.
I'll implement in updated code.
